### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_5_HomeScope#56]
Major:
- [x] Most most important plots on top #75 
- [x] Remove one scatter plot and create dropdown for chosing y-axis. Put map into the empty grid spot. #59 
- [x] Turn histogram into density and one color per city #72 
- [x] Think about a side bar background color #75 

Minor:
- [x] #63
- [x] Combine legends for scatter if there are two #59 
- [x] Numeric inputs more clear that they only control some charts #75 
- [x] Make sure local widgets are close to the plots they control. #75
