### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_5_HomeScope#85]
Implement both major and six of the minor ones

Major:

- [x] Add table on separate tab with all data sortable #110 
- [x] Show selected cities and province in cards, clearly indicate what it #96 

Minor:

- [x] Remove density y-axis? #97 
- [x] Make logo smaller #112 
- [x] Dynamically update dropdown to show only bedrooms? #97 
- [x] Zoom in based #91 
- [x] Highlight selected cities somehow more obviously in the map.
    - Either zoom in, make labels/points bigger  #91 
- [x] Legend repeating colors #91 
- [x] Clearer title on bar plot. #88 
- [x] Remove decimals from cards #95 
- [x] Put numbers outside bars so the they are readable #88
